- name: Deploy on EC2
  uses: appleboy/ssh-action@v1.0.3
  env:
      APP_DIR: /home/${{ secrets.EC2_USER }}/backend
  with:
      host: ${{ secrets.EC2_HOST }}
      username: ${{ secrets.EC2_USER }}
      key: ${{ secrets.EC2_SSH_KEY }}
      script_stop: true
      script: |
          cd /home/${{ secrets.EC2_USER }}/backend

          # Install python-devel, which is required for venv on Amazon Linux
          sudo dnf install -y python3-devel

          # Create the virtual environment
          python3 -m venv .venv

          # Activate the virtual environment
          source .venv/bin/activate

          # Upgrade pip and install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          # Kill any running process on port 8000. 'fuser' needs sudo.
          sudo fuser -k 8000/tcp || true

          # Start the Django server in the background
          nohup python manage.py runserver 0.0.0.0:8000 > logs.out 2>&1 &
          echo "Deployment complete and server restarted!"